apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-cnzz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/susdas_quay_org/mvp-dev-uxos-tenant/mvp-test-app/test-mvp-component-cnzz@sha256:b221e6ca6b25c5e1c4fccbecffbd79a1472e5eee4274beadba25155b6a5f5833
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
